### PR TITLE
Update CI/CD files without automating the integration tests

### PR DESCRIPTION
**Pull request by kbalk**

### CODE REVIEW

**Comment by lorengordon** [comment]
Option 1: You can merge now
Option 2: You can remove the workflow file and I can re-approve
Option 3: You can remove the workflow file and fix the mergify config and I can re-approve

In Options 1 and 2, we'll end up with auto-merged updates on master without running the terraform tests. In Option 3 we'll have dependabot PRs open until someone gets around to running the test manually.

Any of the above will be fine, with 3 being best.

**Comment by kbalk** [comment]
> In addition, the dependabot config file would need to be updated to monitor the path `tests/create_rr_association/prereq`... It's not currently, which is why we are not getting PRs from dependabot for the vpc updates. Oops.
> 
> In the mergify config, I _think_ we can have add a condition like `label!=terraform` and it will skip merging terraform updates while still merging others... We did something similar in watchmaker to condition the actions depending on the type of update... https://github.com/plus3it/watchmaker/blob/main/.mergify.yml

If you look at the master branch, the `.github/workflows/main.yml` does look for "/tests/create_rr_association/prereq"; but `main.yml` was removed in the WIP PR and then you asked for it to be removed from this PR.

How do you test that sort of change?

**Comment by lorengordon** [comment]
Do you want to remove `.github/workflows/main.yml` also, before merging this?

**Comment by kbalk** [comment]
> Do you want to remove `.github/workflows/main.yml` also, before merging this?

Yes, I just noticed that.  Also, there is a reference to "gomod" in dependabot.yml that I want to remove.

**Pull request merged**
